cat head.html step_1.js tail.html > step_1.html
cat head.html step_2.js tail.html > step_2.html
cat head.html step_3.js tail.html > step_3.html
cat head.html step_4.js tail.html > step_4.html
cat head.html step_5.js tail.html > step_5.html
cat head.html step_6.js tail.html > step_6.html
cat head.html step_7.js tail.html > step_7.html
cat head.html step_8.js tail.html > step_8.html
cat head.html step_9.js tail.html > step_9.html
